export function getElements() {
  return {
    sectionTabs: Array.from(document.querySelectorAll("[data-section-target]")),
    sections: Array.from(document.querySelectorAll(".view-section")),
    form: document.getElementById("player-form"),
    input: document.getElementById("tag-input"),
    searchButton: document.getElementById("search-button"),
    statusText: document.getElementById("status"),
    playerPanel: document.getElementById("player-panel"),
    countrySelect: document.getElementById("country-select"),
    rankingTypeSelect: document.getElementById("ranking-type"),
    brawlerSelect: document.getElementById("brawler-select"),
    rankingButton: document.getElementById("load-ranking"),
    locationInfoButton: document.getElementById("location-info-button"),
    locationInfoPanel: document.getElementById("location-info-panel"),
    reloadLocationsButton: document.getElementById("reload-locations-button"),
    brawlerDetailButton: document.getElementById("brawler-detail-button"),
    brawlerDetailPanel: document.getElementById("brawler-detail-panel"),
    rankingList: document.getElementById("ranking-list"),
    clubForm: document.getElementById("club-form"),
    clubInput: document.getElementById("club-tag-input"),
    clubButton: document.getElementById("club-search-button"),
    clubStatus: document.getElementById("club-status"),
    clubPanel: document.getElementById("club-panel"),
    eventsButton: document.getElementById("events-load-button"),
    eventsStatus: document.getElementById("events-status"),
    eventsList: document.getElementById("events-list"),
    multiForm: document.getElementById("multi-form"),
    multiInput: document.getElementById("multi-input"),
    multiButton: document.getElementById("multi-button"),
    multiStatus: document.getElementById("multi-status"),
    multiList: document.getElementById("multi-list"),
    authStatus: document.getElementById("auth-status"),
    loginButton: document.getElementById("login-button"),
    logoutButton: document.getElementById("logout-button")
  };
}
